### ISSUE TITLE
安装完了报错 erro:0

### ISSUE THREAD

**Issue by qunge5211314** [iHongRen/pptp-vpn#3]
大神，可以加个QQ吗？不太会用这个软件呢，安装时报没有这个文件，我又建目录和文件，安装什么也不提示了，以为成功了，还是报erro:0，我QQ635343793，在线等

**Comment by iHongRen** [comment]
能否给个截图，用的是release版？还是自己编译的

**Comment by qunge5211314** [comment]
最开始用的release版，报erro：0  后来使用自己编译，还是报erro：0，github我不太会截图，加QQ可以么，QQ发给您

**Comment by iHongRen** [comment]
bug已修复，版本更新[v1.0.1](https://github.com/iHongRen/pptp-vpn/releases)
